### ISSUE TITLE
Add contributor and maintainer info

### ISSUE THREAD

**Issue by jezcope** [data-lessons/library-git#15]
Add maintainers to the `README` and contributors to `AUTHORS`, as per data-lessons/librarycarpentry#8

**Comment by drjwbaker** [comment]
@jezcope: I was planning to do this for all the lessons as per https://github.com/data-lessons/librarycarpentry/issues/8 but if you want to take it on for the Git lesson, fine (I have it down as a task for tomorrow!)

**Comment by jezcope** [comment]
@drjwbaker Not desperate to do it myself, in fact it probably makes sense for one person to do it all in one batch — just adding the issue for completeness but I may have been a little overzealous!

**Comment by drjwbaker** [comment]
Okay. I'll close it when it is done!

**Comment by drjwbaker** [comment]
Done https://github.com/data-lessons/librarycarpentry/issues/8#issuecomment-247557734
