### ISSUE TITLE
Using nano command in Git Bash

### ISSUE THREAD

**Issue by VictorE87** [data-lessons/library-git#2]
In the part about the git commands there is given an example to make changes to the test file using nano. I installed Git Bash, but then I got the message that the nano command was not found. I would suggest for Windows users to tell them how to install nano or otherwise tell them to change the testfile in Notepad (++).

**Comment by mkuzak** [comment]
I think Notepad ++ is a good choice. This is also a choice in Software Carpentry workshops.
