### ISSUE TITLE
Consistency of lessons titles. 

### ISSUE THREAD

**Issue by yasmina85** [data-lessons/library-git#24]
The lessons' titles on the schedule of the main page of "Git Intro for Librarians" lesson needs to be consistent. Here is the page: http://data-lessons.github.io/library-git/

**Comment by jduckles** [comment]
@yasmina85 What is it that you're seeing as specifically inconsistent about them?

**Comment by mttrb** [comment]
@yasmina85 I've fixed up the capitalisation of the questions in the schedule on the main page.  Is this the inconsistency you noticed?

**Comment by yasmina85** [comment]
@mttrb Yes, Thanks!

**Comment by weaverbel** [comment]
This seems to be resolved so I will close this issue.
