### ISSUE TITLE
GitHub pages episode

### ISSUE THREAD

**Issue by alexandermendes** [data-lessons/library-git#31]
As raised in #7 we can add a GitHub pages episode towards the end. We probably want to keep this as simple as possible but it could be a useful exercise to help people become more comfortable with branching and pushing etc.

**Comment by evanwill** [comment]
I could work on this, maybe once the rest of the lesson settles. 

There is basically four ways to use gh-pages:
1. add an `index.html` file (and any other random HTML)
2. use Automatic Theme Chooser (basically a one page project site based on the `README.md`)
3. add a `_config.yml` and use gh-pages automated Jekyll build service (generate the site from a few `md` files in Minima theme)
4. add a full Jekyll project and use gh-pages automated build

In my own workshops I have introduced options 1 - 3 ([basic](https://evanwill.github.io/go-go-ghpages/2-basic.html) and ([jekyll](https://evanwill.github.io/go-go-ghpages/3-jekyll.html)) fruitfully, but find 4 requires a lot more time and energy ([advanced](https://evanwill.github.io/go-go-ghpages/4-jekyll-advanced.html)).

In this context, maybe just option 1 or 2 (introduced by creating a repo, clone, edit, push, activate gh-pages)?

**Comment by alexandermendes** [comment]
My current idea was to lead into this from the previous episodes. So I've just tidied up episode two, which ends up with a locally committed index.md file containing "# Hello, world!". I suppose the next stage would be pushing to GitHub, then all of the forking and branching stuff. Then, by the time they get to the GitHub pages episode we can say something along the lines of there being a special branch on GitHub called gh-pages, create and push this branch (which you now know how to do) and you have just published a webpage. Might be a nice result for people to see something online with a few commands.

Perhaps this could be followed by something more complex, but it is tricky to know how far to go with this. They might have already taken in enough by this stage! What do you think?

**Comment by alexandermendes** [comment]
Also, I haven't done anything with this episode yet so if you want to work on it we shouldn't have any merging issues etc.

**Comment by evanwill** [comment]
yeah, I wouldn't use it to introduce a new Git concept, but just repeat/reinforce what they learned in the previous episodes. You can now run gh-pages from any branch, so even branching is unnecessary (and undesirable if the main purpose of the repo is to host a site). This would introduce the idea of gh-pages, hinting at the wonderful possibilities, but not adding too much cognitive load.

If they have a repository with an `index.md`, then we could: 
- simply activate gh-pages to see the `md` rendered
- use the Theme Chooser to create a simple page with one click. 
- create a Minima Jekyll site by adding a `_config.yml`.

**Comment by kirschbombe** [comment]
Another option is to have them use an HTML5 template from HTML5Up or something similar. They can get a more interesting page up pretty quickly without having to get into Jekyll. https://html5up.net. I taught this yesterday and introduced Chrome Developer Tools to do some quick styling/customization before pushing up to GitHub.

**Comment by alexandermendes** [comment]
All sound like good ideas to me! 

I suppose the only thing to be wary of is that this is towards the end of a lesson (probably?), so we might be running out of time. I don't have any experience with teaching groups like this, so other people will know better, but I know it can generally take people a long time to get their heads around just the basic commands.

I think leading towards a basic GitHub pages site does make it a bit more interesting, just not sure about that balance, or in fact how we can make this at least vaguely relate to libraries!

**Comment by alexandermendes** [comment]
Closing this as it will sit here for ages otherwise! The lesson has been updated a little, issue can be raised again if someone wants to do more
