### ISSUE TITLE
Lesson structure

### ISSUE THREAD

**Issue by alexandermendes** [data-lessons/library-git#32]
There are obviously plenty of tutorials out there already that start along the lines of

- git init
- git add/remove
- git push/pull

But as mention in https://github.com/data-lessons/library-git/issues/7#issuecomment-305725705 this isn't really how people are likely to use git/github. Probably start with something more along the lines of:

- Create a repo
- Edit a file and push changes (with git diff, git status etc)
- Add/Remove
- Fork someone else's code (going on to PRs?)
- ...

**Comment by kirschbombe** [comment]
Recently I've been focusing my lessons around git/GitHub workflows - so defining 3-4 ways that someone might work (Fork/Pull Requests; starting with a new GitHub repo; initializing an existing directory) and having a mini-lesson for each. This approach seems to bring a little clarity to the workflows.

**Comment by alexandermendes** [comment]
This has been open for a while, closing it as the lesson seems to have moved on a fair bit since!
