### ISSUE TITLE
Disperse "06-Git in Libraries" into "05-Review" and "01-Info" and deleting

### ISSUE THREAD

**Issue by ndalyrose** [data-lessons/library-git#36]
Good points here under [http://data-lessons.github.io/library-git/06-git-in-libraries/](http://data-lessons.github.io/library-git/06-git-in-libraries/). Suggest some could be turned into scenarios for under 01-intro and the rest make up a revised Review activity focussed on considering the contexts in which Git and GitHub could be useful for Libraries.

**Comment by alexandermendes** [comment]
Yep, I think this lesson can just be removed entirely as it's only duplicating info in the intro.
