### ISSUE TITLE
Sentence structure (extra words)

### ISSUE THREAD

**Issue by dakane1** [data-lessons/library-git#47]
Being a bit persnickety, I know we don't read these out but I'm thinking of those that read the lessons to learn.

1. In "Getting Started,"  "Tracking files in Git" section, starts with...if we opted for colourised output, we can see that the file... we don't need the "got."  Sentence reads better without it. 

2.  In "Sharing your work," "Pushing Changes" section, start with "say we are very forgetful and have already forgotten what we changes we have made.  We don't need the second "we."

**Comment by weaverbel** [comment]
Fixed now @dakane1  - thanks for spotting them.
