### ISSUE TITLE
Building static sites using GitHub pages in second hour

### ISSUE THREAD

**Issue by davanstrien** [data-lessons/library-git#6]
* I think the original schedule for this session is unrealistic for most groups. A smaller group with more experience on command line tools may cruise through the first hour but I think there will usually be issues with installation etc that need to be addressed. 

* A good starting point for doing something on building websites with GitHub pages would be [Building a static website with Jekyll and GitHub Pages](http://programminghistorian.org/lessons/building-static-sites-with-jekyll-github-pages) a Programming Historian lesson. This lesson probably covers too much but might be a useful further resource.

**Comment by drjwbaker** [comment]
We need someone to take this on. I'll ping the Gitter..

**Comment by auremoser** [comment]
We built a [template for gh-pages curriculum](https://github.com/mozillascience/working-open-workshop), resulting [site looks like this](http://mozillascience.github.io/working-open-workshop/), if you'd like to crib it and change the .less to suit your design, it's a simple jekyll structure for teaching materials. 

You can adapt it in an hour. :)

**Comment by weaverbel** [comment]
@drjwbaker @davanstrien Could @auremoser 's template work for LC?

**Comment by cmacdonell** [comment]
I think this piece http://mozillascience.github.io/working-open-workshop/github_for_collaboration/ might be the most relevant

**Comment by auremoser** [comment]
Base template is [here](https://github.com/mozillascience/working-open-workshop/tree/gh-pages/template). the Github for Collaboration lesson is [here](https://github.com/mozillascience/working-open-workshop/tree/gh-pages/github_for_collaboration).

**Comment by weaverbel** [comment]
Thanks @auremoser !

**Comment by weaverbel** [comment]
@cmacdonell  - what about this? https://github.com/gvwilson/new-lesson-example

**Comment by cmacdonell** [comment]
@auremoser you say it is a jekyll structure, but was the html created by jekyll?

**Comment by auremoser** [comment]
Ah derp sorry, I messed that up, it's our [study groups](https://github.com/mozillascience/studyGroup) repo that's a Jekyll structure with a template site, but this one is just .js/.html/.less in directories.

**Comment by jezcope** [comment]
There's also been a recent discussion on the Software Carpentry discussion list ([starting with this message](http://lists.software-carpentry.org/pipermail/discuss/2016-May/004473.html)), kicked off by a [blog post about teaching git using github pages to build a blog](http://bgran.de/teaching-git-using-github-pages/).

**Comment by auremoser** [comment]
Dan Sinker made a repo that uses modular taco recipes to teach git: https://github.com/sinker/tacofancy

**Comment by cmacdonell** [comment]
Ya, I kinda the idea of simple text content (like recipes or stories), I would worry with blogs some people might get caught up on appearance tweaking rather than content.

**Comment by weaverbel** [comment]
I think most of this has been resolved with work done on the lessons so I am closing this issue.
