### ISSUE TITLE
Move content over to gh-pages

### ISSUE THREAD

**Issue by jezcope** [data-lessons/library-git#8]
Looks like @cmacdonell has set up a `gh-pages` branch using the SWC/DC template but it currently needs filling in, so here's an issue to track progress on that.

[SQL for libraries](http://data-lessons.github.io/library-sql/) ([github repo](https://github.com/data-lessons/library-sql)) has already made a start on this, for reference.

- [x] Move lesson content to `_episodes`
- [ ] Move content from `handout.md` into the appropriate place
- [ ] Tidy up the formatting in line with [guidance](https://gvwilson.github.io/new-lesson-example/02-formatting/)

**Comment by weaverbel** [comment]
@jezcope I've merged your PR

**Comment by weaverbel** [comment]
I think we are good here with content migrated so I am closing this issue.
