### ISSUE TITLE
Develop learning objectives for git lesson

### ISSUE THREAD

**Issue by jezcope** [data-lessons/library-git#9]
It will be helpful to have a defined set of learning objectives for the lesson.

**Comment by michielcock** [comment]
This would be my suggestion:

"After completing this lesson, you can:

* explain why version control is useful
* explain the difference between git and Github
* use the shell commands to do basic version control with git
* set up a website using Github Pages"

**Comment by weaverbel** [comment]
Proposing slightly new wording @michielcock 

"After completing this lesson, you will be able to:

- understand the benefits of automated version control 
- understand basic version control using Git
- set up a website using Github Pages

**Comment by michielcock** [comment]
I tried to use only measurable verbs in describing the learning objective: what is the observable behavior of a student after completing the lesson? "Set up a website" does that, but "understand" doesn't. That's why I chose "explain", but any other verb from the same domain (e.g., "describe", "summarize") could be used as well.

All other changes are OK with me.

**Comment by jezcope** [comment]
I agree with @michielcock on using measurable verbs. Also, now that I've been through the lesson template it's clear that there's an expectation of having one or two learning objectives for each section ("episode") of the lesson: see, for example, the pink overview box on [this page](http://data-lessons.github.io/library-git/02-getting-started/).

Prompted by that, here are two more possible objectives:

- Share your work and collaborate using GitHub
- Assess the role of git in a library context

**Comment by jezcope** [comment]
That last one relating to #7.

**Comment by weaverbel** [comment]
I have added these to the episodes so I am closing this issue.
